[2022-06-08 08:59:57] [INFO] [Recovery] 2022/06/08 - 08:59:57 panic recovered:
Get "https://192.168.111.100:6443/version?timeout=32s": dial tcp 192.168.111.100:6443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
C:/Users/mensyli1/work/workspace/mwpath/pkg/mod/github.com/toolkits/pkg@v1.2.9/errorx/errorx.go:40 (0x23d21ca)
	Dangerous: }
C:/Users/mensyli1/work/workspace/mwpath/pkg/mod/github.com/toolkits/pkg@v1.2.9/ginx/errorx.go:10 (0x241879b)
	Dangerous: }
C:/Users/mensyli1/work/workspace/middleware/src/controller/postgres/postgres.go:62 (0x241e064)
	GetPostgresByName: }
C:/Users/mensyli1/work/workspace/mwpath/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165 (0x237d59c)
	(*Context).Next: c.index++
C:/Users/mensyli1/work/workspace/middleware/src/util/aop/jwt.go:19 (0x242196e)
	Auth.func1: 
C:/Users/mensyli1/work/workspace/mwpath/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165 (0x237d59c)
	(*Context).Next: c.index++
C:/Users/mensyli1/work/workspace/middleware/src/util/aop/logrus.go:62 (0x24219fa)
	Logrus.func1: //ÁªìÊùüÊó∂Èó¥
C:/Users/mensyli1/work/workspace/mwpath/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165 (0x237d59c)
	(*Context).Next: c.index++
C:/Users/mensyli1/work/workspace/middleware/src/util/aop/recovery.go:94 (0x241fdc4)
	CustomRecoveryWithWriter.func1: }
C:/Users/mensyli1/work/workspace/mwpath/pkg/mod/github.com/gin-gonic/gin@v1.7.4/context.go:165 (0x237d59c)
	(*Context).Next: c.index++
C:/Users/mensyli1/work/workspace/mwpath/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:489 (0x238b993)
	(*Engine).handleHTTPRequest: c.writermem.WriteHeaderNow()
C:/Users/mensyli1/work/workspace/mwpath/pkg/mod/github.com/gin-gonic/gin@v1.7.4/gin.go:445 (0x238b49a)
	(*Engine).ServeHTTP: 
C:/install/Dev/Env/Go/src/net/http/server.go:2879 (0xff2e39)
	serverHandler.ServeHTTP: }
C:/install/Dev/Env/Go/src/net/http/server.go:1930 (0xfec977)
	(*conn).serve: w.cancelCtx()
C:/install/Dev/Env/Go/src/runtime/asm_amd64.s:1581 (0xbb89c0)
	goexit: CALL	runtime¬∑goexit1(SB)	// does not return
[0m (github.com/mensylisir/kmpp-middleware/src/util/aop.CustomRecoveryWithWriter.func1.1: 82) {map[]} 
[2022-06-08 08:59:57] [ERROR] gather cluster info error: Get "https://192.168.111.100:6443/version?timeout=32s": dial tcp 192.168.111.100:6443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (github.com/mensylisir/kmpp-middleware/src/cron/job.(*WatchClusterInfo).Run.func1: 34) {map[]} 
[2022-06-08 08:59:57] [ERROR] gather postgres info error: Get "https://192.168.111.100:6443/version?timeout=32s": dial tcp 192.168.111.100:6443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (github.com/mensylisir/kmpp-middleware/src/cron/job.(*WatchPostgresqlInfo).Run.func1: 35) {map[]} 
[2022-06-08 08:59:57] [ERROR] gather postgres info error: Get "https://192.168.111.100:6443/version?timeout=32s": dial tcp 192.168.111.100:6443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (github.com/mensylisir/kmpp-middleware/src/cron/job.(*WatchPostgresqlInfo).Run.func1: 35) {map[]} 
